"""Tests for the snow17 Fortran shim (fortran/snow17_shim.f90).

Three tests CLAUDE.md calls out as required before writing the Tesseract
wrapper, in order of how much they're trusted:

1. test_determinism         -- catches COMMON-block leakage between calls
2. test_state_continuity    -- sharper version of (1); trust this one most
3. test_mass_balance        -- catches unit errors (mm/s vs mm/step)

Plus a bonus cross-check against reference output shipped with the
vendored snow17 checkout (test_cases/ex1), generated by the same
EXSNOW19/PACK19 we call, via the upstream BMI driver.
"""

import ctypes
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from snow17 import Snow17Params, run_snow17  # noqa: E402

EX1_DIR = REPO_ROOT / "external" / "snow17" / "test_cases" / "ex1"


def _ensure_ex1_extracted():
    """test_cases/ex1 ships as a .tgz in the submodule; extract on first use
    so a fresh `git submodule update --init` + `pytest` just works."""
    if EX1_DIR.exists():
        return
    import tarfile

    tgz = EX1_DIR.parent / "ex1.tgz"
    with tarfile.open(tgz) as tf:
        tf.extractall(EX1_DIR.parent)


_ensure_ex1_extracted()


# ---------------------------------------------------------------------------
# ex1 (HHWM8) fixtures -- real forcing/params/reference output shipped
# upstream, used for the mass-balance and reference-cross-check tests.
# ---------------------------------------------------------------------------

def _load_ex1_params(hru_id: str) -> Snow17Params:
    text = (EX1_DIR / "input" / "params" / "snow17_params.HHWM8.txt").read_text()
    rows = [line.split() for line in text.strip().splitlines()]
    header = rows[0]
    col = header.index(hru_id)
    values = {row[0]: row[col] for row in rows[1:]}
    adc = np.array([float(values[f"adc{i}"]) for i in range(1, 12)], dtype=np.float32)
    return Snow17Params(
        alat=float(values["latitude"]),
        elev=float(values["elev"]),
        scf=float(values["scf"]),
        mfmax=float(values["mfmax"]),
        mfmin=float(values["mfmin"]),
        uadj=float(values["uadj"]),
        si=float(values["si"]),
        nmf=float(values["nmf"]),
        tipm=float(values["tipm"]),
        mbase=float(values["mbase"]),
        pxtemp=float(values["pxtemp"]),
        plwhc=float(values["plwhc"]),
        daygm=float(values["daygm"]),
        adc=adc,
    )


def _load_ex1_forcing(hru_id: str):
    """Returns (dates, pcp_mm_per_day, tmp_degc). pcp converted mm/s -> mm/day."""
    df = pd.read_csv(EX1_DIR / "input" / "forcing" / f"forcing.snow17bmi.{hru_id}.csv")
    dates = pd.DatetimeIndex(
        pd.to_datetime(df[["year", "mo", "dy"]].rename(columns={"mo": "month", "dy": "day"}))
    )
    idts = 86400
    pcp = (df["prec_mm_s-1"].to_numpy(dtype=np.float64) * idts).astype(np.float32)
    tmp = df["tavg_degc"].to_numpy(dtype=np.float32)
    return dates, pcp, tmp


def _load_ex1_reference(hru_id: str) -> pd.DataFrame:
    path = EX1_DIR / "output" / f"output.snow17bmi.{hru_id}.txt"
    return pd.read_csv(path, sep=r"\s+")


# ---------------------------------------------------------------------------
# Synthetic fixture for determinism / continuity: doesn't need to be
# physically realistic, just needs to exercise accumulation and melt so
# state actually moves through its various branches (new-snow line,
# depletion curve, liquid water storage, excess lag).
# ---------------------------------------------------------------------------

def _synthetic_series(n=200, seed=0):
    rng = np.random.default_rng(seed)
    dates = pd.date_range("2001-01-01", periods=n, freq="D")
    pcp = rng.gamma(shape=1.0, scale=3.0, size=n).astype(np.float32)
    # seasonal-ish temperature so we see both accumulation and melt
    doy = np.arange(n)
    tmp = (10 * np.sin(2 * np.pi * doy / 365 - np.pi / 2) + rng.normal(0, 3, n)).astype(np.float32)
    return dates, pcp, tmp


def _default_params():
    return Snow17Params(
        alat=47.78, elev=1612.5, scf=1.15, mfmax=1.05, mfmin=0.15,
        uadj=0.04, si=500.0, nmf=0.15, tipm=0.2, mbase=0.0,
        pxtemp=1.0, plwhc=0.03, daygm=0.0,
        adc=np.array([0.05, 0.09, 0.16, 0.31, 0.54, 0.74, 0.84, 0.89, 0.93, 0.97, 1.0], dtype=np.float32),
    )


# ---------------------------------------------------------------------------
# 1. Determinism
# ---------------------------------------------------------------------------

def test_determinism():
    dates, pcp, tmp = _synthetic_series()
    params = _default_params()

    out1 = run_snow17(dates, pcp, tmp, params)
    out2 = run_snow17(dates, pcp, tmp, params)

    np.testing.assert_array_equal(out1.raim, out2.raim)
    np.testing.assert_array_equal(out1.sneqv, out2.sneqv)
    np.testing.assert_array_equal(out1.snowh, out2.snowh)
    np.testing.assert_array_equal(out1.cs, out2.cs)
    assert out1.tprev == out2.tprev


# ---------------------------------------------------------------------------
# 2. State continuity: one long call == two chained calls
# ---------------------------------------------------------------------------

def test_state_continuity():
    dates, pcp, tmp = _synthetic_series(n=100)
    params = _default_params()

    whole = run_snow17(dates, pcp, tmp, params)

    first = run_snow17(dates[:50], pcp[:50], tmp[:50], params)
    second = run_snow17(
        dates[50:], pcp[50:], tmp[50:], params,
        cs0=first.cs, tprev0=first.tprev,
    )
    chained_raim = np.concatenate([first.raim, second.raim])
    chained_sneqv = np.concatenate([first.sneqv, second.sneqv])
    chained_snowh = np.concatenate([first.snowh, second.snowh])

    np.testing.assert_array_equal(whole.raim, chained_raim)
    np.testing.assert_array_equal(whole.sneqv, chained_sneqv)
    np.testing.assert_array_equal(whole.snowh, chained_snowh)
    np.testing.assert_array_equal(whole.cs, second.cs)
    assert whole.tprev == second.tprev


# ---------------------------------------------------------------------------
# 3. Mass balance over a full water year of real forcing
# ---------------------------------------------------------------------------

def test_mass_balance():
    hru_id = "HHWM8IL"
    params = _load_ex1_params(hru_id)
    dates, pcp, tmp = _load_ex1_forcing(hru_id)

    # water year 1971: 1970-10-01 .. 1971-09-30, cold start at the
    # beginning of a water year keeps initial storage close to zero.
    mask = (dates >= "1970-10-01") & (dates <= "1971-09-30")
    dates_wy, pcp_wy, tmp_wy = dates[mask], pcp[mask], tmp[mask]
    assert len(dates_wy) == 365

    out = run_snow17(dates_wy, pcp_wy, tmp_wy, params)

    # SCF (gauge undercatch correction) applies only to the snow fraction
    # of precip, not rain -- see PACK19.f: `SFALL=PXI*FRACS*SCF` where
    # FRACS/FRACR come from a hard TA-vs-PXTEMP threshold (PACK19.f:104).
    # Confirmed by first computing this the naive way (pcp * scf applied
    # uniformly) and finding a ~25% imbalance that vanished once the
    # rain/snow split was applied -- see notes/NOTES.md.
    is_snow = tmp_wy <= params.pxtemp
    corrected_pcp = np.where(is_snow, pcp_wy * params.scf, pcp_wy)

    total_input = float(np.sum(corrected_pcp))                # mm
    total_raim = float(np.sum(out.raim))                      # mm
    delta_swe = float(out.sneqv[-1] - 0.0) * 1000.0            # mm; cold start SWE0=0

    balance_error = total_input - (total_raim + delta_swe)
    # snow17 has no evap/sublimation term, so this should close tightly;
    # allow a small tolerance for float32 accumulation over 365 steps.
    assert abs(balance_error) < 1e-2 * total_input, (
        f"mass balance off by {balance_error:.3f} mm "
        f"({100*balance_error/total_input:.4f}% of input={total_input:.1f} mm), "
        f"raim={total_raim:.1f} mm, delta_swe={delta_swe:.1f} mm"
    )


# ---------------------------------------------------------------------------
# Bonus: cross-check against reference output shipped with the vendored
# checkout (same EXSNOW19/PACK19, run through the upstream BMI driver).
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("hru_id", ["HHWM8IL", "HHWM8IU"])
def test_matches_upstream_reference(hru_id):
    params = _load_ex1_params(hru_id)
    dates, pcp, tmp = _load_ex1_forcing(hru_id)
    ref = _load_ex1_reference(hru_id)
    assert len(ref) == len(dates)

    out = run_snow17(dates, pcp, tmp, params)

    # Reference sneqv is written as sneqv_m*1000 (mm); ours is metres.
    # These two are the quantities that matter (raim feeds SAC-SMA (or HBV, fallback-only); sneqv is
    # the mass state) and they match to float32 precision.
    np.testing.assert_allclose(out.raim, ref["raim"].to_numpy(), atol=5e-3, rtol=1e-3)
    np.testing.assert_allclose(out.sneqv * 1000.0, ref["sneqv"].to_numpy(), atol=5e-3, rtol=1e-3)


@pytest.mark.parametrize("hru_id", ["HHWM8IL", "HHWM8IU"])
def test_snowh_divergence_is_explained_by_upstream_tprev_bug(hru_id):
    """snowh (depth) does NOT match the reference directly -- explained,
    not silently ignored. See notes/NOTES.md.

    runSnow17.f90 allocates modelvar%tprev(:) = 0.0 once and never
    reassigns it for a cold-start run (grep confirms no other write site),
    so the reference output was generated with TPREV pinned at 0.0 for
    every timestep of the 46-year run, not the previous day's air temp.
    TPREV only feeds DTA=TA-TPREV in the density/compaction submodel
    (SNOWT.f/SNOWPACK.f) -- it doesn't touch mass (WE) or RAIM, which is
    why those matched exactly regardless of this choice.

    Our shim tracks TPREV as the actual previous timestep's temperature
    (the physically sensible reading of "previous air temperature"),
    which is why our snowh differs from upstream's. Proof: pinning TPREV
    at 0.0 exactly like the upstream driver reproduces its snowh output
    to float32 precision.
    """
    params = _load_ex1_params(hru_id)
    dates, pcp, tmp = _load_ex1_forcing(hru_id)
    ref = _load_ex1_reference(hru_id)

    n = len(pcp)
    cs = np.zeros(19, dtype=np.float32)
    adc11 = np.ascontiguousarray(params.adc, dtype=np.float32)
    raim = np.empty(1, dtype=np.float32)
    sneqv = np.empty(1, dtype=np.float32)
    snowh = np.empty(n, dtype=np.float32)
    iyr = np.asarray(dates.year, dtype=np.int32)
    imn = np.asarray(dates.month, dtype=np.int32)
    ida = np.asarray(dates.day, dtype=np.int32)
    pcp32 = pcp.astype(np.float32)
    tmp32 = tmp.astype(np.float32)

    from snow17 import _LIB

    for t in range(n):
        tprev_pinned = ctypes.c_float(0.0)  # replicate upstream: never updated
        _LIB.snow17_run(
            1, 24, 86400,
            iyr[t:t + 1], imn[t:t + 1], ida[t:t + 1],
            pcp32[t:t + 1], tmp32[t:t + 1],
            params.alat, params.elev, params.scf, params.mfmax, params.mfmin,
            params.uadj, params.si, params.nmf, params.tipm, params.mbase,
            params.pxtemp, params.plwhc, params.daygm,
            adc11, cs, ctypes.byref(tprev_pinned),
            raim, sneqv, snowh[t:t + 1],
        )

    np.testing.assert_allclose(snowh, ref["snowh"].to_numpy(), atol=5e-3, rtol=1e-3)
